-- Migration: añadir niveles estructurales ICT AMD a las tablas *_bars
-- Campos: asian_high/low, prev_day_high/low, swing_high/low_50, equal_high/low
-- Necesarios para backtest de la estrategia ICT AMD / Liquidity Sweep

ALTER TABLE btc_bars
    ADD COLUMN IF NOT EXISTS asian_high    DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS asian_low     DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS prev_day_high DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS prev_day_low  DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS swing_high_50 DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS swing_low_50  DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS equal_high    BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS equal_low     BOOLEAN DEFAULT FALSE;

ALTER TABLE eth_bars
    ADD COLUMN IF NOT EXISTS asian_high    DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS asian_low     DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS prev_day_high DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS prev_day_low  DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS swing_high_50 DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS swing_low_50  DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS equal_high    BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS equal_low     BOOLEAN DEFAULT FALSE;

ALTER TABLE bnb_bars
    ADD COLUMN IF NOT EXISTS asian_high    DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS asian_low     DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS prev_day_high DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS prev_day_low  DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS swing_high_50 DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS swing_low_50  DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS equal_high    BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS equal_low     BOOLEAN DEFAULT FALSE;

ALTER TABLE sol_bars
    ADD COLUMN IF NOT EXISTS asian_high    DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS asian_low     DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS prev_day_high DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS prev_day_low  DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS swing_high_50 DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS swing_low_50  DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS equal_high    BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS equal_low     BOOLEAN DEFAULT FALSE;
