name: CI

on:
  push:
  pull_request:

jobs:
  rust:
    name: Rust
    runs-on: windows-latest
    env:
      CARGO_BUILD_TARGET: x86_64-pc-windows-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1.95.0
        with:
          components: clippy,rustfmt
          targets: x86_64-pc-windows-gnu

      - name: Install MinGW
        run: choco install mingw -y

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Check
        run: cargo check --workspace --all-targets

      - name: Test
        run: cargo test --workspace --all-targets

      - name: Install cargo-audit
        run: cargo install cargo-audit --locked

      - name: Audit dependencies
        run: cargo audit

      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
